name: Run Python Script on Pull Request

on:
  pull_request:
    branches:
      - main # change this to your main branch

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: DARPA-CRITICALMAAS/ta2-minmod-kg
          ref: main

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.11 # change this to your desired Python version

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r validators/requirements.txt  # change this if you have dependencies

      - uses: actions/checkout@v3
        with:
          path: "."
          key: ${{ runner.os }}-build

      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: "json"
      - run: |
          pwd
          # echo '${{ steps.files.outputs.all }}' >> changed_files.json
          # echo '${{ steps.files.outputs.all }}'
          # cat changed_files.json

          ls $GITHUB_WORKSPACE

        # for changed_file in ${{ steps.files.outputs.all }}; do
        #     TEMP_FILE=$(mktemp)
        #     python validators/validate_schema_github_actions.py ${changed_file} ${TEMP_FILE} ${{ secrets.BEARER_TOKEN }} ${{ github.event.pull_request.head.ref }}
        #   done
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: test
          path: "."
